### ISSUE TITLE
App closes immediately in DEBUG

### ISSUE THREAD

**Issue by philipengberg** [lmirosevic/GBJailbreakDetection#1]
After installing `3.2.0` of `GBDeviceInfo` and thus installing this library, my app consistently and immediately closes when debugging on the simulator. I get no exception, no errors what so ever.

Running Xcode 6.4 and iOS 8.4.

**Comment by lmirosevic** [comment]
Make sure the DEBUG flag is set. This library has a failsafe to prevent attachment of a debugger to make it harder to reverse-engineer. Code for this is actually open-source: https://github.com/lmirosevic/GBDeviceInfo/blob/master/GBDeviceInfo/GBDeviceInfo_iOS.m#L322-337
