### ISSUE TITLE
XCode 7 Warnings

### ISSUE THREAD

**Issue by jerome-miastkowski** [lmirosevic/GBJailbreakDetection#3]
Hello,

After updating to XCode 7 and updating the GBDeviceInfo pod we are receiving the following warning:

ld: warning: object file (/Users/USER_NAME/Documents/Git Repositories/APP_NAME/ios/Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o)) was built for newer iOS version (8.2) than being linked (7.1)

We would still like to support iOS 7.1 and >, so changing the minimum version is not an option.

And about 16 warnings like this:

warning: /Users/lm/Library/Developer/Xcode/DerivedData/ModuleCache/3VKQVBP6KHSD5/Foundation-3DFYNEBRQSXST.pcm: No such file or directory

We have tried clearing the derived data without any change.

Any ideas would be greatly appreciated.

**Comment by lmirosevic** [comment]
Should be fixed with the latest version `1.1.1`

**Comment by lmirosevic** [comment]
Actually, `1.1.1` only fixed the first set of warnings, the second set is fixed in `1.2.0`
